name: docker-lint
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  # Can look up error with https://github.com/hadolint/hadolint/wiki/DL3029
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - run: docker run -v --rm -i hadolint/hadolint hadolint --failure-threshold warning - < great_expectations_cloud/agent/Dockerfile
